version: "3.4"
services:
  nginx:
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./baack/docker/nginx/conf.d:/etc/nginx/conf.d/ # config
      - ./frontend/stardeos/build:/public_html # public html       
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  