version: '3.4'
services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ../db:/data/db
      - ../mongo/script/:/script/
      - ../mongo/setup/:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=davichosoadmin
      - MONGO_INITDB_ROOT_PASSWORD=davichosoxd333
      - USER=davichosouser
      - USER_PASSWD=davichosoxd333xd
      - DBNAME=stardeos
#    command: bash -c "mongod --repair && mongod"
    restart: always

#docker exec mongodb sh -c 'mongodump --authenticationDatabase admin -u inmobileadmin -p davichosoxd333 --db inmobile --archive' > db.dump
#docker-compose exec -T mongodb sh -c 'mongodump --authenticationDatabase admin -u inmobileadmin -p davichosoxd333 --db inmobile --archive' > db.dump
#docker-compose exec -T mongodb sh -c 'mongorestore --authenticationDatabase admin -u inmobileadmin -p davichosoxd333 --db inmobile --archive' < db.dump